name: Deploy theme to Xserver

on:
  push:
    branches:
      - main

jobs:
  ftps-deploy:
    name: FTPS deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Xserver
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./
          server-dir: /sub-sup.net/public_html/wp-content/themes/subsup/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**
